services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  mysql-data: 